### ISSUE TITLE
Error auto deploying when entering a password with special character.

### ISSUE THREAD

**Issue by lastbattle** [sonm-io/autodeploy#4]
I've pointed this out in the betatest chat, just for reference here.. 

![e5813e8c-b2cd-430f-8d72-6bb663bfafa2](https://user-images.githubusercontent.com/4586194/43542539-dffa948e-95ff-11e8-8878-839e45a0bb38.jpg)

If the password for the worker address that you setup contains some special character, the installation might fail...

a long password that consist of all of the following: 
 , 
 '
 ;
[
]
.

**Comment by eaxvac** [comment]
![6f7322d2-e548-4656-9796-8def45a32634](https://user-images.githubusercontent.com/4586194/43656159-f57158b8-9783-11e8-8f20-34d5884d9b3d.jpg)

The same issue exist for passwords in /home/sonm/.sonm/cli.yaml too.!

**Comment by 3Hren** [comment]
Probable we should wrap passwords with `""` with proper escaping.

**Comment by avsigaev** [comment]
Fixed - installation script does not ask for password (strong password for local admin key is redundant).
